version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "composer"
    directory: "/"
    registries: "*"
    open-pull-requests-limit: 15
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/docs"
    open-pull-requests-limit: 15
    schedule:
      interval: "weekly"
