name: PHP Linting

on: [push, pull_request]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: "laravel-pint"
          uses: aglipanci/laravel-pint-action@2.3.1
          with:
            testMode: true
            useComposer: true
            configPath: "pint.json"