name: PHP Tests

on: [pull_request]

jobs:
  lint:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://ghcr.io/php-cs-fixer/php-cs-fixer:3-php8.2
        with:
          args: check
  test:
    name: Test on PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.0', '8.1', '8.2']
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@v3

      - name: Run phpunit
        run: vendor/bin/phpunit --verbose
